// This file is auto-generated by @hey-api/openapi-ts

export type AIFinancialSummary = {
    headline?: string;
    summary?: string;
    period?: string;
    key_metrics?: Array<AIKeyMetric>;
    strengths?: Array<(string)>;
    concerns?: Array<(string)>;
    recommendations?: Array<AIRecommendation>;
    fact_sheet?: {
        [key: string]: unknown;
    };
    generated_at?: (string | null);
};

export type AIKeyMetric = {
    label?: string;
    value?: string;
    trend?: string;
};

export type AIRecommendation = {
    title?: string;
    rationale?: string;
    priority?: string;
};

export type AuditLogPublic = {
    company_id?: (string | null);
    user_id?: (string | null);
    module: string;
    table_name: string;
    record_id?: (string | null);
    action: string;
    entity_name?: (string | null);
    description: string;
    old_data?: ({
    [key: string]: unknown;
} | null);
    new_data?: ({
    [key: string]: unknown;
} | null);
    log_metadata?: ({
    [key: string]: unknown;
} | null);
    ip_address?: (string | null);
    user_agent?: (string | null);
    created_at?: string;
    id: number;
    user_email?: (string | null);
    user_full_name?: (string | null);
    company_name?: (string | null);
};

export type AuditLogsPublic = {
    data: Array<AuditLogPublic>;
    count: number;
};

export type BankAccountCreate = {
    bank_name: string;
    account_name: string;
    account_number: string;
    account_type: string;
    opening_balance?: number;
    opening_date?: string;
    notes?: string;
    company_id?: (string | null);
    user_id?: (string | null);
};

export type BankAccountPublic = {
    bank_name: string;
    account_name: string;
    account_number: string;
    account_type: string;
    opening_balance?: number;
    opening_date?: string;
    notes?: string;
    company_id?: (string | null);
    user_id?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type BankAccountsPublic = {
    data: Array<BankAccountPublic>;
    count: number;
};

export type BankAccountUpdate = {
    bank_name?: (string | null);
    account_name?: (string | null);
    account_number?: (string | null);
    account_type?: (string | null);
    opening_balance?: (number | null);
    opening_date?: (string | null);
    notes?: (string | null);
    company_id?: (string | null);
};

export type BankImportSessionPublic = {
    company_id?: (string | null);
    user_id?: (string | null);
    source_type?: string;
    file_name?: (string | null);
    bank_name?: (string | null);
    statement_start?: (string | null);
    statement_end?: (string | null);
    status?: string;
    duplicate_count?: number;
    transaction_count?: number;
    created_at?: (string | null);
    updated_at?: (string | null);
    completed_at?: (string | null);
    id: string;
};

export type BankImportSessionsPublic = {
    data: Array<BankImportSessionPublic>;
    count: number;
};

export type BankImportTransactionPublic = {
    session_id: string;
    company_id?: (string | null);
    date: string;
    description: string;
    reference?: (string | null);
    amount: number;
    debit?: number;
    credit?: number;
    balance?: (number | null);
    raw_data?: {
        [key: string]: unknown;
    };
    ai_status?: string;
    ai_transaction_type?: string;
    ai_category?: (string | null);
    ai_confidence?: number;
    ai_reason?: string;
    ai_suggested_action?: string;
    reconciliation_status?: string;
    selected?: boolean;
    final_action?: string;
    final_category?: (string | null);
    matched_record_type?: (string | null);
    matched_record_id?: (string | null);
    match_confidence?: (number | null);
    match_reason?: (string | null);
    is_duplicate?: boolean;
    duplicate_of_transaction_id?: (string | null);
    ignored_reason?: (string | null);
    created_record_type?: (string | null);
    created_record_id?: (string | null);
    applied_by?: (string | null);
    applied_at?: (string | null);
    created_at?: (string | null);
    id: string;
};

export type BankReconciliationApplyRequest = {
    transaction_ids?: (Array<(string)> | null);
};

export type BankReconciliationApplyResponse = {
    created_expenses?: number;
    created_revenues?: number;
    matched?: number;
    ignored?: number;
    skipped?: number;
};

export type BankReconciliationBulkUpdate = {
    transaction_ids: Array<(string)>;
    selected?: (boolean | null);
    final_action?: (string | null);
    final_category?: (string | null);
    reconciliation_status?: (string | null);
};

export type BankReconciliationSessionDetail = {
    session: BankImportSessionPublic;
    transactions: Array<BankImportTransactionPublic>;
    summary: BankReconciliationSummary;
};

export type BankReconciliationSummary = {
    total?: number;
    matched?: number;
    needs_review?: number;
    suggested_expenses?: number;
    suggested_revenues?: number;
    duplicates?: number;
    ignored?: number;
    applied?: number;
};

export type BankReconciliationTransactionUpdate = {
    selected?: (boolean | null);
    final_action?: (string | null);
    final_category?: (string | null);
    reconciliation_status?: (string | null);
    matched_record_type?: (string | null);
    matched_record_id?: (string | null);
    ignored_reason?: (string | null);
};

export type BankReconciliationUploadResponse = {
    session: BankImportSessionPublic;
    transactions: Array<BankImportTransactionPublic>;
    summary: BankReconciliationSummary;
    warnings?: Array<(string)>;
};

export type Body_bank_reconciliation_upload_bank_statement = {
    file: (Blob | File);
    ocr_text?: (string | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_uploads_upload_company_logo = {
    file: (Blob | File);
};

export type CapitalAllowanceDetail = {
    purchase_id?: (string | null);
    asset: string;
    purchase_date: string;
    purchase_cost: number;
    asset_class: string;
    initial_allowance_rate: number;
    annual_allowance_rate: number;
    initial_allowance: number;
    annual_allowance: number;
    total_allowance: number;
    remaining_qualifying_expenditure: number;
    review_warning?: (string | null);
};

/**
 * Payload to initiate a subscription purchase checkout.
 */
export type CheckoutRequest = {
    plan: string;
    billing_interval: string;
};

/**
 * Response containing CHIP Collect checkout URL and reference.
 */
export type CheckoutResponse = {
    checkout_url: string;
    reference: string;
};

export type ClientCreate = {
    name: string;
    email: string;
    phone_number?: (string | null);
    company_name?: (string | null);
    customer_type: string;
    reg_number?: (string | null);
    billing_address?: (string | null);
    company_id?: (string | null);
    user_id?: (string | null);
};

export type ClientPublic = {
    name: string;
    email: string;
    phone_number?: (string | null);
    company_name?: (string | null);
    customer_type: string;
    reg_number?: (string | null);
    billing_address?: (string | null);
    company_id?: (string | null);
    user_id?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type ClientsPublic = {
    data: Array<ClientPublic>;
    count: number;
};

export type ClientUpdate = {
    name?: (string | null);
    email?: (string | null);
    phone_number?: (string | null);
    company_name?: (string | null);
    customer_type?: (string | null);
    reg_number?: (string | null);
    billing_address?: (string | null);
    company_id?: (string | null);
};

export type CompaniesPublic = {
    data: Array<CompanyPublic>;
    count: number;
};

export type CompanyCreate = {
    company_name: string;
    currency: string;
    registration_number?: (string | null);
    company_email: string;
    phone_number: string;
    company_url?: (string | null);
    company_address?: (string | null);
    is_active?: boolean;
    document_running_numbers?: {
        [key: string]: (number);
    };
    employee_size?: (string | null);
    business_industry?: (string | null);
    company_type?: (string | null);
    financial_year_end?: (string | null);
    sst_registration_number?: (string | null);
    einvoice_required?: boolean;
    default_document_template_id?: (string | null);
    other_personal_taxable_income?: number;
};

export type CompanyPublic = {
    company_name: string;
    currency: string;
    registration_number?: (string | null);
    company_email: string;
    phone_number: string;
    company_url?: (string | null);
    company_address?: (string | null);
    is_active?: boolean;
    document_running_numbers?: {
        [key: string]: (number);
    };
    employee_size?: (string | null);
    business_industry?: (string | null);
    company_type?: (string | null);
    financial_year_end?: (string | null);
    sst_registration_number?: (string | null);
    einvoice_required?: boolean;
    default_document_template_id?: (string | null);
    other_personal_taxable_income?: number;
    id: string;
    user_id?: (string | null);
};

export type CompanyUpdate = {
    company_name?: (string | null);
    currency?: (string | null);
    registration_number?: (string | null);
    company_email?: (string | null);
    phone_number?: (string | null);
    company_url?: (string | null);
    company_address?: (string | null);
    is_active?: (boolean | null);
    document_running_numbers?: ({
    [key: string]: (number);
} | null);
    employee_size?: (string | null);
    business_industry?: (string | null);
    company_type?: (string | null);
    financial_year_end?: (string | null);
    sst_registration_number?: (string | null);
    einvoice_required?: (boolean | null);
    default_document_template_id?: (string | null);
    other_personal_taxable_income?: (number | null);
};

export type DashboardChartData = {
    sales_overview?: Array<MonthlyDataPoint>;
    purchases_overview?: Array<MonthlyDataPoint>;
    total_revenue?: number;
    total_expenses?: number;
};

export type DashboardSummary = {
    total_revenue?: number;
    total_expenses?: number;
};

export type DocumentCreate = {
    company_id?: (string | null);
    user_id?: (string | null);
    docno: string;
    doctype: string;
    client_id?: (string | null);
    date?: string;
    title: string;
    item?: (Array<{
    [key: string]: unknown;
}> | {
    [key: string]: unknown;
});
    price_calculation?: {
        [key: string]: unknown;
    };
    remark?: string;
    status: string;
    validity?: (string | null);
    duedate?: (string | null);
    generated_from_recurring_id?: (string | null);
    stock_deducted?: boolean;
};

export type DocumentDefaultNotePublic = {
    document_type: string;
    default_notes_enabled?: boolean;
    default_notes?: string;
    id: string;
    company_id?: (string | null);
};

export type DocumentDefaultNotesPublic = {
    data: Array<DocumentDefaultNotePublic>;
};

export type DocumentDefaultNoteUpdate = {
    default_notes_enabled?: (boolean | null);
    default_notes?: (string | null);
};

export type DocumentPublic = {
    company_id?: (string | null);
    user_id?: (string | null);
    docno: string;
    doctype: string;
    client_id?: (string | null);
    date?: string;
    title: string;
    item?: (Array<{
    [key: string]: unknown;
}> | {
    [key: string]: unknown;
});
    price_calculation?: {
        [key: string]: unknown;
    };
    remark?: string;
    status: string;
    validity?: (string | null);
    duedate?: (string | null);
    generated_from_recurring_id?: (string | null);
    stock_deducted?: boolean;
    id: string;
};

export type DocumentsPublic = {
    data: Array<DocumentPublic>;
    count: number;
};

export type DocumentTemplatePublic = {
    name: string;
    code: string;
    description?: (string | null);
    is_default?: boolean;
    is_active?: boolean;
    id: string;
};

export type DocumentTemplatesPublic = {
    data: Array<DocumentTemplatePublic>;
};

export type DocumentUpdate = {
    company_id?: (string | null);
    user_id?: (string | null);
    docno?: (string | null);
    doctype?: (string | null);
    client_id?: (string | null);
    date?: (string | null);
    title?: (string | null);
    item?: (Array<{
    [key: string]: unknown;
}> | {
    [key: string]: unknown;
} | null);
    price_calculation?: ({
    [key: string]: unknown;
} | null);
    remark?: (string | null);
    status?: (string | null);
    validity?: (string | null);
    duedate?: (string | null);
    generated_from_recurring_id?: (string | null);
    stock_deducted?: (boolean | null);
};

export type EmailCampaignCreate = {
    subject: string;
    body: string;
    filter_json?: {
        [key: string]: unknown;
    };
};

export type EmailCampaignPublic = {
    subject: string;
    body: string;
    filter_json?: {
        [key: string]: unknown;
    };
    recipient_count?: (number | null);
    status?: string;
    id: string;
    created_by?: (string | null);
    created_at?: (string | null);
    sent_at?: (string | null);
};

export type EmailCampaignRecipientPublic = {
    campaign_id: string;
    user_id?: (string | null);
    email: string;
    status?: string;
    error_message?: (string | null);
    id: string;
    sent_at?: (string | null);
};

export type EmailCampaignRecipientsPublic = {
    data: Array<EmailCampaignRecipientPublic>;
    count: number;
};

export type EmailCampaignsPublic = {
    data: Array<EmailCampaignPublic>;
    count: number;
};

export type EmailCampaignUpdate = {
    subject?: (string | null);
    body?: (string | null);
    filter_json?: ({
    [key: string]: unknown;
} | null);
    status?: (string | null);
};

export type EmailTemplateCreate = {
    name: string;
    description?: (string | null);
    subject: string;
    body: string;
};

export type EmailTemplatePublic = {
    name: string;
    description?: (string | null);
    subject: string;
    body: string;
    id: string;
    created_by?: (string | null);
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type EmailTemplatesPublic = {
    data: Array<EmailTemplatePublic>;
    count: number;
};

export type EmailTemplateUpdate = {
    name?: (string | null);
    description?: (string | null);
    subject?: (string | null);
    body?: (string | null);
};

/**
 * Public representation of entitlement status for a feature.
 */
export type EntitlementStatusPublic = {
    feature: string;
    plan: string;
    limit?: (number | null);
    current_usage: number;
    over_limit: boolean;
    can_create: boolean;
};

export type ExpenseCategoryDeduction = {
    category: string;
    total_recorded: number;
    tax_treatment: string;
    estimated_deductible: number;
    requires_review: boolean;
    notes?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ImportBulkRequest = {
    import_type: string;
    company_id?: (string | null);
    records: Array<ImportDraftRecord>;
    batch_size?: number;
};

export type ImportBulkResponse = {
    imported: number;
    failed: number;
    skipped: number;
    processing_time_ms: number;
    results: Array<ImportBulkResult>;
};

export type ImportBulkResult = {
    row_number: number;
    status: string;
    errors?: Array<(string)>;
};

export type ImportDraftRecord = {
    row_number: number;
    data?: {
        [key: string]: unknown;
    };
    original_row?: {
        [key: string]: unknown;
    };
    selected?: boolean;
};

export type ImportField = {
    key: string;
    label: string;
    type: string;
    required?: boolean;
    unique?: boolean;
    aliases?: Array<(string)>;
    default?: (unknown | null);
};

export type ImportFieldList = {
    import_type: string;
    fields: Array<ImportField>;
};

export type ImportValidatedRecord = {
    row_number: number;
    selected?: boolean;
    status: string;
    errors?: Array<(string)>;
    original_row?: {
        [key: string]: unknown;
    };
    data?: {
        [key: string]: unknown;
    };
};

export type ImportValidationRequest = {
    import_type: string;
    company_id?: (string | null);
    records: Array<ImportDraftRecord>;
};

export type ImportValidationResponse = {
    records: Array<ImportValidatedRecord>;
    total_rows: number;
    valid_rows: number;
    invalid_rows: number;
};

export type IntegrationCreate = {
    company_id?: (string | null);
    platform: string;
    access_token: string;
    refresh_token?: (string | null);
    expires_at?: (string | null);
};

export type IntegrationPublic = {
    company_id?: (string | null);
    platform: string;
    access_token: string;
    refresh_token?: (string | null);
    expires_at?: (string | null);
    id: string;
};

export type IntegrationsPublic = {
    data: Array<IntegrationPublic>;
    count: number;
};

export type IntegrationUpdate = {
    company_id?: (string | null);
    platform?: (string | null);
    access_token?: (string | null);
    refresh_token?: (string | null);
    expires_at?: (string | null);
};

export type InventoryTransactionPublic = {
    product_id: string;
    document_id?: (string | null);
    document_number?: string;
    quantity_deducted?: number;
    previous_stock?: number;
    new_stock?: number;
    company_id?: (string | null);
    user_id?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type InventoryTransactionsPublic = {
    data: Array<InventoryTransactionPublic>;
    count: number;
};

export type Message = {
    message: string;
};

export type MonthlyDataPoint = {
    month?: string;
    total?: number;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

/**
 * Warning item when an expired subscription's current resources exceed personal limits.
 */
export type OverLimitWarningPublic = {
    feature: string;
    label: string;
    current: number;
    limit: number;
    message: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ProductCategoriesPublic = {
    data: Array<(string)>;
};

export type ProductCreate = {
    product_name: string;
    description?: (string | null);
    sku?: (string | null);
    category?: string;
    cost_price?: number;
    sell_price?: number;
    supplier?: (string | null);
    stock_quantity?: number;
    unit_type?: string;
    company_id?: (string | null);
    user_id?: (string | null);
};

export type ProductPublic = {
    product_name: string;
    description?: (string | null);
    sku?: (string | null);
    category?: string;
    cost_price?: number;
    sell_price?: number;
    supplier?: (string | null);
    stock_quantity?: number;
    unit_type?: string;
    company_id?: (string | null);
    user_id?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type ProductsPublic = {
    data: Array<ProductPublic>;
    count: number;
};

export type ProductUpdate = {
    product_name?: (string | null);
    description?: (string | null);
    sku?: (string | null);
    category?: (string | null);
    cost_price?: (number | null);
    sell_price?: (number | null);
    supplier?: (string | null);
    stock_quantity?: (number | null);
    unit_type?: (string | null);
    company_id?: (string | null);
};

export type PurchaseCreate = {
    date: string;
    due_date?: (string | null);
    supplier_name: string;
    category: string;
    company_id?: (string | null);
    user_id?: (string | null);
    amount: number;
    tax: number;
    final_amount: number;
    status: string;
    invoice_no?: (string | null);
    notes?: string;
};

export type PurchasePublic = {
    date: string;
    due_date?: (string | null);
    supplier_name: string;
    category: string;
    company_id?: (string | null);
    user_id?: (string | null);
    amount: number;
    tax: number;
    final_amount: number;
    status: string;
    invoice_no?: (string | null);
    notes?: string;
    id: string;
};

export type PurchasesPublic = {
    data: Array<PurchasePublic>;
    count: number;
};

export type PurchasesSuppliersPublic = {
    data: Array<(string)>;
};

export type PurchaseUpdate = {
    date?: (string | null);
    due_date?: (string | null);
    supplier_name?: (string | null);
    category?: (string | null);
    company_id?: (string | null);
    user_id?: (string | null);
    amount?: (number | null);
    tax?: (number | null);
    final_amount?: (number | null);
    status?: (string | null);
    invoice_no?: (string | null);
    notes?: (string | null);
};

export type ReceiptParseRequest = {
    text: string;
};

export type ReceiptParseResult = {
    supplier_name?: (string | null);
    date?: (string | null);
    due_date?: (string | null);
    category?: (string | null);
    invoice_no?: (string | null);
    amount?: (number | null);
    tax?: (number | null);
    description?: (string | null);
};

export type RecipientCountResponse = {
    count: number;
};

/**
 * Filter spec for resolving email campaign recipients.
 * All fields are optional; combine freely. selected_user_ids always
 * adds those users regardless of other filters.
 */
export type RecipientFilter = {
    all_users?: boolean;
    new_users_days?: (number | null);
    active_within_days?: (number | null);
    onboarding_completed?: (boolean | null);
    active_only?: boolean;
    superusers_only?: boolean;
    selected_user_ids?: Array<(string)>;
};

export type RecurringConfigCreate = {
    company_id?: (string | null);
    user_id?: (string | null);
    name: string;
    frequency?: string;
    interval?: number;
    start_date?: string;
    end_date?: (string | null);
    next_run_date?: (string | null);
    last_run_date?: (string | null);
    due_after_days?: number;
    auto_send?: boolean;
    recipient_email?: (string | null);
    generated_count?: number;
    max_occurrences?: (number | null);
    status?: string;
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type RecurringConfigPublic = {
    company_id?: (string | null);
    user_id?: (string | null);
    name: string;
    frequency?: string;
    interval?: number;
    start_date?: string;
    end_date?: (string | null);
    next_run_date?: (string | null);
    last_run_date?: (string | null);
    due_after_days?: number;
    auto_send?: boolean;
    recipient_email?: (string | null);
    generated_count?: number;
    max_occurrences?: (number | null);
    status?: string;
    created_at?: (string | null);
    updated_at?: (string | null);
    id: string;
};

export type RecurringConfigUpdate = {
    name?: (string | null);
    frequency?: (string | null);
    interval?: (number | null);
    start_date?: (string | null);
    end_date?: (string | null);
    next_run_date?: (string | null);
    last_run_date?: (string | null);
    due_after_days?: (number | null);
    auto_send?: (boolean | null);
    recipient_email?: (string | null);
    generated_count?: (number | null);
    max_occurrences?: (number | null);
    status?: (string | null);
};

export type RecurringDocCreate = {
    company_id?: (string | null);
    user_id?: (string | null);
    recurring_config_id?: (string | null);
    doctype?: string;
    client_id?: (string | null);
    date?: string;
    title: string;
    item?: (Array<{
    [key: string]: unknown;
}> | {
    [key: string]: unknown;
});
    price_calculation?: {
        [key: string]: unknown;
    };
    remark?: string;
    status?: string;
    validity?: (string | null);
    duedate?: (string | null);
};

export type RecurringDocUpdate = {
    company_id?: (string | null);
    user_id?: (string | null);
    recurring_config_id?: (string | null);
    doctype?: (string | null);
    client_id?: (string | null);
    date?: (string | null);
    title?: (string | null);
    item?: (Array<{
    [key: string]: unknown;
}> | {
    [key: string]: unknown;
} | null);
    price_calculation?: ({
    [key: string]: unknown;
} | null);
    remark?: (string | null);
    status?: (string | null);
    validity?: (string | null);
    duedate?: (string | null);
};

export type RecurringScheduleCreate = {
    schedule: RecurringConfigCreate;
    template: RecurringDocCreate;
    generate_immediately?: boolean;
};

export type RecurringScheduleUpdate = {
    schedule?: (RecurringConfigUpdate | null);
    template?: (RecurringDocUpdate | null);
};

export type SaleCreate = {
    date?: string;
    channel: string;
    notes?: string;
    company_id?: (string | null);
    user_id?: (string | null);
    gross_amount: number;
    discount: number;
    net_sales: number;
    cancel_amount: number;
    short_over: number;
    refund: number;
    final_amount: number;
    status: string;
};

export type SalePublic = {
    date?: string;
    channel: string;
    notes?: string;
    company_id?: (string | null);
    user_id?: (string | null);
    gross_amount: number;
    discount: number;
    net_sales: number;
    cancel_amount: number;
    short_over: number;
    refund: number;
    final_amount: number;
    status: string;
    id: string;
};

export type SalesChannelsPublic = {
    data: Array<(string)>;
};

export type SalesPublic = {
    data: Array<SalePublic>;
    count: number;
};

export type SaleUpdate = {
    date?: (string | null);
    channel?: (string | null);
    notes?: (string | null);
    company_id?: (string | null);
    user_id?: (string | null);
    gross_amount?: (number | null);
    discount?: (number | null);
    net_sales?: (number | null);
    cancel_amount?: (number | null);
    short_over?: (number | null);
    refund?: (number | null);
    final_amount?: (number | null);
    status?: (string | null);
};

export type SendTestEmailRequest = {
    email_to: string;
    subject: string;
    body: string;
};

export type StaffAdd = {
    email: string;
};

export type StaffMemberPublic = {
    id: string;
    name?: (string | null);
    email: string;
    phone_number?: (string | null);
    avatar?: (string | null);
    membership_type: string;
};

export type StaffPublic = {
    data: Array<StaffMemberPublic>;
    count: number;
};

/**
 * Consolidated subscription management overview details.
 */
export type SubscriptionDetailsPublic = {
    plan: string;
    effective_plan?: string;
    status: string;
    billing_interval?: (string | null);
    current_period_start?: (string | null);
    current_period_end?: (string | null);
    cancel_at_period_end?: boolean;
    is_approaching_expiry?: boolean;
    days_until_expiry?: (number | null);
    is_expired?: boolean;
    limits: {
        [key: string]: unknown;
    };
    usage: {
        [key: string]: unknown;
    };
    over_limit_warnings?: Array<OverLimitWarningPublic>;
    subscription_history?: Array<SubscriptionHistoryPublic>;
    payment_history?: Array<UserPaymentPublic>;
};

/**
 * Public representation of a past subscription period event.
 */
export type SubscriptionHistoryPublic = {
    plan: string;
    billing_interval?: (string | null);
    period?: (string | null);
    status: string;
    created_at?: (string | null);
};

/**
 * Payload to renew an existing paid subscription.
 */
export type SubscriptionRenewRequest = {
    billing_interval?: (string | null);
};

/**
 * Response returned upon successfully creating a renewal payment purchase.
 */
export type SubscriptionRenewResponse = {
    checkout_url: string;
    reference: string;
};

export type TaxAdvisorAnalysis = {
    company_id: string;
    tax_year: number;
    taxpayer_type: string;
    revenue: number;
    expenses: number;
    profit_before_tax: number;
    deductible_expenses: number;
    conditional_expenses: number;
    non_deductible_expenses: number;
    capital_allowance: number;
    tax_adjustments: number;
    chargeable_income: number;
    other_personal_taxable_income?: number;
    combined_taxable_income?: number;
    estimated_tax_payable: number;
    effective_tax_rate: number;
    marginal_tax_rate: number;
    tax_paid: number;
    tax_remaining: number;
    overpaid_amount: number;
    tax_brackets?: Array<TaxBracketBreakdown>;
    deductions_by_category?: Array<ExpenseCategoryDeduction>;
    capital_allowance_details?: Array<CapitalAllowanceDetail>;
    requires_review?: Array<(string)>;
    warnings?: Array<(string)>;
};

export type TaxBracketBreakdown = {
    bracket: string;
    min_amount: number;
    max_amount?: (number | null);
    taxable_amount: number;
    rate: number;
    tax: number;
};

export type TaxPaymentCreate = {
    company_id: string;
    user_id?: (string | null);
    tax_year: number;
    payment_date?: string;
    amount: number;
    payment_type?: string;
    reference?: (string | null);
    notes?: (string | null);
};

export type TaxPaymentPublic = {
    company_id: string;
    user_id?: (string | null);
    tax_year: number;
    payment_date?: string;
    amount: number;
    payment_type?: string;
    reference?: (string | null);
    notes?: (string | null);
    id: string;
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type TaxPaymentsPublic = {
    data: Array<TaxPaymentPublic>;
    count: number;
};

export type TaxRateBracketPublic = {
    tax_rule_set_id: string;
    sequence: number;
    min_amount: number;
    max_amount?: (number | null);
    rate: number;
    description: string;
    id: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    birthdate?: (string | null);
    phone_number?: (string | null);
    role?: string;
    company_id?: (string | null);
    companies?: string;
    last_login_at?: (string | null);
    onboarding_completed?: boolean;
    email_verified?: boolean;
    email_verified_at?: (string | null);
    has_completed_tour?: boolean;
    completed_tour_at?: (string | null);
    password: string;
};

/**
 * Public representation of a user's subscription payment record.
 */
export type UserPaymentPublic = {
    id: string;
    provider: string;
    plan: string;
    billing_interval: string;
    amount: number;
    currency: string;
    status: string;
    reference: string;
    paid_at?: (string | null);
    created_at: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    birthdate?: (string | null);
    phone_number?: (string | null);
    role?: string;
    company_id?: (string | null);
    companies?: string;
    last_login_at?: (string | null);
    onboarding_completed?: boolean;
    email_verified?: boolean;
    email_verified_at?: (string | null);
    has_completed_tour?: boolean;
    completed_tour_at?: (string | null);
    id: string;
    created_at?: (string | null);
    plan?: (string | null);
    billing_period?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
    birthdate?: (string | null);
    phone_number?: (string | null);
};

export type UserSearchResult = {
    id: string;
    full_name?: (string | null);
    email: string;
};

export type UserSearchResults = {
    data: Array<UserSearchResult>;
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

/**
 * Public representation of a user's current subscription.
 */
export type UserSubscriptionPublic = {
    plan: string;
    effective_plan?: string;
    billing_period?: (string | null);
    status: string;
    started_at?: (string | null);
    expires_at?: (string | null);
    cancel_at_period_end?: boolean;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    birthdate?: (string | null);
    phone_number?: (string | null);
    role?: string;
    company_id?: (string | null);
    companies?: string;
    last_login_at?: (string | null);
    onboarding_completed?: boolean;
    email_verified?: boolean;
    email_verified_at?: (string | null);
    has_completed_tour?: (boolean | null);
    completed_tour_at?: (string | null);
    password?: (string | null);
    plan?: (string | null);
    billing_period?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
    birthdate?: (string | null);
    phone_number?: (string | null);
    company_id?: (string | null);
    has_completed_tour?: (boolean | null);
    completed_tour_at?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type VerifyEmailRequest = {
    token: string;
};

export type AiReadFinancialSummaryResponse = (AIFinancialSummary);

export type AiGenerateFinancialSummaryData = {
    /**
     * Preset period: this_week, last_7_days, month_to_date, year_to_date, last_6_months, last_12_months, all_time
     */
    period?: string;
};

export type AiGenerateFinancialSummaryResponse = (AIFinancialSummary);

export type AiReadAiInsightData = {
    moduleType: "financial_summary";
};

export type AiReadAiInsightResponse = (AIFinancialSummary);

export type AiGenerateAiInsightRouteData = {
    moduleType: "financial_summary";
    /**
     * Preset period: this_week, last_7_days, month_to_date, year_to_date, last_6_months, last_12_months, all_time
     */
    period?: string;
};

export type AiGenerateAiInsightRouteResponse = (AIFinancialSummary);

export type AiParseReceiptData = {
    requestBody: ReceiptParseRequest;
};

export type AiParseReceiptResponse = (ReceiptParseResult);

export type AuditLogsReadAuditLogsData = {
    action?: (string | null);
    companyId?: (string | null);
    endDate?: (string | null);
    keyword?: (string | null);
    limit?: number;
    module?: (string | null);
    recordId?: (string | null);
    skip?: number;
    startDate?: (string | null);
    tableName?: (string | null);
    userId?: (string | null);
};

export type AuditLogsReadAuditLogsResponse = (AuditLogsPublic);

export type AuditLogsReadAuditLogs1Data = {
    action?: (string | null);
    companyId?: (string | null);
    endDate?: (string | null);
    keyword?: (string | null);
    limit?: number;
    module?: (string | null);
    recordId?: (string | null);
    skip?: number;
    startDate?: (string | null);
    tableName?: (string | null);
    userId?: (string | null);
};

export type AuditLogsReadAuditLogs1Response = (AuditLogsPublic);

export type AuditLogsReadAuditLogByIdData = {
    id: number;
};

export type AuditLogsReadAuditLogByIdResponse = (AuditLogPublic);

export type AuthVerifyEmailData = {
    requestBody: VerifyEmailRequest;
};

export type AuthVerifyEmailResponse = (Message);

export type AuthResendVerificationResponse = (Message);

export type BankAccountsReadBankAccountsData = {
    companyId?: (string | null);
    limit?: number;
    skip?: number;
};

export type BankAccountsReadBankAccountsResponse = (BankAccountsPublic);

export type BankAccountsCreateBankAccountData = {
    requestBody: BankAccountCreate;
};

export type BankAccountsCreateBankAccountResponse = (BankAccountPublic);

export type BankAccountsReadBankAccountData = {
    id: string;
};

export type BankAccountsReadBankAccountResponse = (BankAccountPublic);

export type BankAccountsUpdateBankAccountData = {
    id: string;
    requestBody: BankAccountUpdate;
};

export type BankAccountsUpdateBankAccountResponse = (BankAccountPublic);

export type BankAccountsDeleteBankAccountData = {
    id: string;
};

export type BankAccountsDeleteBankAccountResponse = (Message);

export type BankReconciliationReadBankImportSessionsData = {
    companyId?: (string | null);
    limit?: number;
    skip?: number;
};

export type BankReconciliationReadBankImportSessionsResponse = (BankImportSessionsPublic);

export type BankReconciliationReadBankImportSessionData = {
    sessionId: string;
};

export type BankReconciliationReadBankImportSessionResponse = (BankReconciliationSessionDetail);

export type BankReconciliationUploadBankStatementData = {
    companyId?: (string | null);
    formData: Body_bank_reconciliation_upload_bank_statement;
};

export type BankReconciliationUploadBankStatementResponse = (BankReconciliationUploadResponse);

export type BankReconciliationUpdateBankTransactionData = {
    requestBody: BankReconciliationTransactionUpdate;
    transactionId: string;
};

export type BankReconciliationUpdateBankTransactionResponse = (BankImportTransactionPublic);

export type BankReconciliationBulkUpdateBankTransactionsData = {
    requestBody: BankReconciliationBulkUpdate;
    sessionId: string;
};

export type BankReconciliationBulkUpdateBankTransactionsResponse = (BankReconciliationSessionDetail);

export type BankReconciliationApplyBankReconciliationData = {
    requestBody: BankReconciliationApplyRequest;
    sessionId: string;
};

export type BankReconciliationApplyBankReconciliationResponse = (BankReconciliationApplyResponse);

export type ClientsReadClientsData = {
    companyId?: (string | null);
    limit?: number;
    skip?: number;
};

export type ClientsReadClientsResponse = (ClientsPublic);

export type ClientsCreateClientData = {
    requestBody: ClientCreate;
};

export type ClientsCreateClientResponse = (ClientPublic);

export type ClientsReadClientData = {
    id: string;
};

export type ClientsReadClientResponse = (ClientPublic);

export type ClientsUpdateClientData = {
    id: string;
    requestBody: ClientUpdate;
};

export type ClientsUpdateClientResponse = (ClientPublic);

export type ClientsDeleteClientData = {
    id: string;
};

export type ClientsDeleteClientResponse = (Message);

export type CompaniesReadCompaniesData = {
    limit?: number;
    skip?: number;
};

export type CompaniesReadCompaniesResponse = (CompaniesPublic);

export type CompaniesCreateCompanyData = {
    requestBody: CompanyCreate;
};

export type CompaniesCreateCompanyResponse = (CompanyPublic);

export type CompaniesReadCompanyData = {
    id: string;
};

export type CompaniesReadCompanyResponse = (CompanyPublic);

export type CompaniesUpdateCompanyData = {
    id: string;
    requestBody: CompanyUpdate;
};

export type CompaniesUpdateCompanyResponse = (CompanyPublic);

export type CompaniesDeleteCompanyData = {
    id: string;
};

export type CompaniesDeleteCompanyResponse = (Message);

export type CompaniesReadCompanyStaffData = {
    companyId: string;
};

export type CompaniesReadCompanyStaffResponse = (StaffPublic);

export type CompaniesAddCompanyStaffData = {
    companyId: string;
    requestBody: StaffAdd;
};

export type CompaniesAddCompanyStaffResponse = (StaffMemberPublic);

export type CompaniesRemoveCompanyStaffData = {
    companyId: string;
    userId: string;
};

export type CompaniesRemoveCompanyStaffResponse = (Message);

export type DashboardReadDashboardSummaryResponse = (DashboardSummary);

export type DashboardReadDashboardChartData = {
    /**
     * End date (YYYY-MM-DD)
     */
    endDate?: (string | null);
    /**
     * Preset period: this_week, last_7_days, month_to_date, all_time, year_to_date, last_6_months, last_12_months
     */
    period?: (string | null);
    /**
     * Start date (YYYY-MM-DD)
     */
    startDate?: (string | null);
};

export type DashboardReadDashboardChartResponse = (DashboardChartData);

export type DocumentDefaultNoteReadDocumentDefaultNotesResponse = (DocumentDefaultNotesPublic);

export type DocumentDefaultNoteUpsertDocumentDefaultNoteData = {
    documentType: string;
    requestBody: DocumentDefaultNoteUpdate;
};

export type DocumentDefaultNoteUpsertDocumentDefaultNoteResponse = (DocumentDefaultNotePublic);

export type DocumentsReadDocumentsData = {
    companyId?: (string | null);
    limit?: number;
    skip?: number;
};

export type DocumentsReadDocumentsResponse = (DocumentsPublic);

export type DocumentsCreateDocumentData = {
    requestBody: DocumentCreate;
};

export type DocumentsCreateDocumentResponse = (DocumentPublic);

export type DocumentsReadDocumentPublicData = {
    id: string;
};

export type DocumentsReadDocumentPublicResponse = ({
    [key: string]: unknown;
});

export type DocumentsReadDocumentData = {
    id: string;
};

export type DocumentsReadDocumentResponse = (DocumentPublic);

export type DocumentsUpdateDocumentData = {
    id: string;
    requestBody: DocumentUpdate;
};

export type DocumentsUpdateDocumentResponse = (DocumentPublic);

export type DocumentsDeleteDocumentData = {
    id: string;
};

export type DocumentsDeleteDocumentResponse = (Message);

export type DocumentsDeductDocumentInventoryData = {
    id: string;
};

export type DocumentsDeductDocumentInventoryResponse = (DocumentPublic);

export type DocumentTemplatesReadDocumentTemplatesResponse = (DocumentTemplatesPublic);

export type EmailBlastingListTemplatesData = {
    limit?: number;
    skip?: number;
};

export type EmailBlastingListTemplatesResponse = (EmailTemplatesPublic);

export type EmailBlastingCreateTemplateData = {
    requestBody: EmailTemplateCreate;
};

export type EmailBlastingCreateTemplateResponse = (EmailTemplatePublic);

export type EmailBlastingGetTemplateData = {
    templateId: string;
};

export type EmailBlastingGetTemplateResponse = (EmailTemplatePublic);

export type EmailBlastingUpdateTemplateData = {
    requestBody: EmailTemplateUpdate;
    templateId: string;
};

export type EmailBlastingUpdateTemplateResponse = (EmailTemplatePublic);

export type EmailBlastingDeleteTemplateData = {
    templateId: string;
};

export type EmailBlastingDeleteTemplateResponse = (Message);

export type EmailBlastingDuplicateTemplateData = {
    templateId: string;
};

export type EmailBlastingDuplicateTemplateResponse = (EmailTemplatePublic);

export type EmailBlastingPreviewRecipientCountData = {
    requestBody: RecipientFilter;
};

export type EmailBlastingPreviewRecipientCountResponse = (RecipientCountResponse);

export type EmailBlastingSearchUsersData = {
    limit?: number;
    q?: string;
};

export type EmailBlastingSearchUsersResponse = (UserSearchResults);

export type EmailBlastingCreateCampaignData = {
    requestBody: EmailCampaignCreate;
};

export type EmailBlastingCreateCampaignResponse = (EmailCampaignPublic);

export type EmailBlastingListCampaignsData = {
    limit?: number;
    skip?: number;
};

export type EmailBlastingListCampaignsResponse = (EmailCampaignsPublic);

export type EmailBlastingGetCampaignData = {
    campaignId: string;
};

export type EmailBlastingGetCampaignResponse = (EmailCampaignPublic);

export type EmailBlastingUpdateCampaignData = {
    campaignId: string;
    requestBody: EmailCampaignUpdate;
};

export type EmailBlastingUpdateCampaignResponse = (EmailCampaignPublic);

export type EmailBlastingSendCampaignData = {
    campaignId: string;
};

export type EmailBlastingSendCampaignResponse = (EmailCampaignPublic);

export type EmailBlastingDuplicateCampaignData = {
    campaignId: string;
};

export type EmailBlastingDuplicateCampaignResponse = (EmailCampaignPublic);

export type EmailBlastingListCampaignRecipientsData = {
    campaignId: string;
    limit?: number;
    skip?: number;
    status?: (string | null);
};

export type EmailBlastingListCampaignRecipientsResponse = (EmailCampaignRecipientsPublic);

export type EmailBlastingSendTestEmailData = {
    requestBody: SendTestEmailRequest;
};

export type EmailBlastingSendTestEmailResponse = (Message);

export type IntegrationsReadIntegrationsData = {
    companyId?: (string | null);
    limit?: number;
    skip?: number;
};

export type IntegrationsReadIntegrationsResponse = (IntegrationsPublic);

export type IntegrationsCreateIntegrationData = {
    requestBody: IntegrationCreate;
};

export type IntegrationsCreateIntegrationResponse = (IntegrationPublic);

export type IntegrationsReadIntegrationData = {
    id: string;
};

export type IntegrationsReadIntegrationResponse = (IntegrationPublic);

export type IntegrationsUpdateIntegrationData = {
    id: string;
    requestBody: IntegrationUpdate;
};

export type IntegrationsUpdateIntegrationResponse = (IntegrationPublic);

export type IntegrationsDeleteIntegrationData = {
    id: string;
};

export type IntegrationsDeleteIntegrationResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PaymentsChipPaymentCallbackResponse = (unknown);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ProductsReadProductsData = {
    companyId?: (string | null);
    limit?: number;
    skip?: number;
};

export type ProductsReadProductsResponse = (ProductsPublic);

export type ProductsCreateProductData = {
    requestBody: ProductCreate;
};

export type ProductsCreateProductResponse = (ProductPublic);

export type ProductsReadProductCategoriesData = {
    companyId?: (string | null);
};

export type ProductsReadProductCategoriesResponse = (ProductCategoriesPublic);

export type ProductsReadProductData = {
    id: string;
};

export type ProductsReadProductResponse = (ProductPublic);

export type ProductsUpdateProductData = {
    id: string;
    requestBody: ProductUpdate;
};

export type ProductsUpdateProductResponse = (ProductPublic);

export type ProductsDeleteProductData = {
    id: string;
};

export type ProductsDeleteProductResponse = (Message);

export type ProductsReadProductInventoryTransactionsData = {
    id: string;
    limit?: number;
    skip?: number;
};

export type ProductsReadProductInventoryTransactionsResponse = (InventoryTransactionsPublic);

export type PurchasesReadPurchasesData = {
    companyId?: (string | null);
    limit?: number;
    skip?: number;
};

export type PurchasesReadPurchasesResponse = (PurchasesPublic);

export type PurchasesCreatePurchaseData = {
    requestBody: PurchaseCreate;
};

export type PurchasesCreatePurchaseResponse = (PurchasePublic);

export type PurchasesReadPurchasesSuppliersData = {
    companyId?: (string | null);
};

export type PurchasesReadPurchasesSuppliersResponse = (PurchasesSuppliersPublic);

export type PurchasesReadPurchaseData = {
    id: string;
};

export type PurchasesReadPurchaseResponse = (PurchasePublic);

export type PurchasesUpdatePurchaseData = {
    id: string;
    requestBody: PurchaseUpdate;
};

export type PurchasesUpdatePurchaseResponse = (PurchasePublic);

export type PurchasesDeletePurchaseData = {
    id: string;
};

export type PurchasesDeletePurchaseResponse = (Message);

export type RecurringReadRecurringConfigsData = {
    companyId?: (string | null);
};

export type RecurringReadRecurringConfigsResponse = ({
    [key: string]: unknown;
});

export type RecurringCreateRecurringData = {
    requestBody: RecurringScheduleCreate;
};

export type RecurringCreateRecurringResponse = ({
    [key: string]: unknown;
});

export type RecurringReadRecurringConfigData = {
    id: string;
};

export type RecurringReadRecurringConfigResponse = ({
    [key: string]: unknown;
});

export type RecurringUpdateRecurringData = {
    id: string;
    requestBody: RecurringScheduleUpdate;
};

export type RecurringUpdateRecurringResponse = ({
    [key: string]: unknown;
});

export type RecurringDeleteRecurringData = {
    id: string;
};

export type RecurringDeleteRecurringResponse = (Message);

export type RecurringPauseRecurringData = {
    id: string;
};

export type RecurringPauseRecurringResponse = (RecurringConfigPublic);

export type RecurringResumeRecurringData = {
    id: string;
};

export type RecurringResumeRecurringResponse = (RecurringConfigPublic);

export type RecurringGenerateNowData = {
    id: string;
};

export type RecurringGenerateNowResponse = ({
    [key: string]: unknown;
});

export type SalesReadSalesData = {
    companyId?: (string | null);
    limit?: number;
    skip?: number;
};

export type SalesReadSalesResponse = (SalesPublic);

export type SalesCreateSaleData = {
    requestBody: SaleCreate;
};

export type SalesCreateSaleResponse = (SalePublic);

export type SalesReadSalesChannelsData = {
    companyId?: (string | null);
};

export type SalesReadSalesChannelsResponse = (SalesChannelsPublic);

export type SalesReadSaleData = {
    id: string;
};

export type SalesReadSaleResponse = (SalePublic);

export type SalesUpdateSaleData = {
    id: string;
    requestBody: SaleUpdate;
};

export type SalesUpdateSaleResponse = (SalePublic);

export type SalesDeleteSaleData = {
    id: string;
};

export type SalesDeleteSaleResponse = (Message);

export type SubscriptionReadSubscriptionResponse = (UserSubscriptionPublic);

export type SubscriptionReadSubscriptionDetailsResponse = (SubscriptionDetailsPublic);

export type SubscriptionRenewSubscriptionCheckoutData = {
    requestBody?: (SubscriptionRenewRequest | null);
};

export type SubscriptionRenewSubscriptionCheckoutResponse = (SubscriptionRenewResponse);

export type SubscriptionCreateSubscriptionCheckoutData = {
    requestBody: CheckoutRequest;
};

export type SubscriptionCreateSubscriptionCheckoutResponse = (CheckoutResponse);

export type SubscriptionReadSubscriptionPaymentsResponse = (Array<UserPaymentPublic>);

export type SubscriptionReadEntitlementStatusData = {
    companyId?: (string | null);
    feature: string;
};

export type SubscriptionReadEntitlementStatusResponse = (EntitlementStatusPublic);

export type TaxAdvisorReadTaxAdvisorYearsData = {
    companyId: string;
};

export type TaxAdvisorReadTaxAdvisorYearsResponse = (Array<(number)>);

export type TaxAdvisorReadTaxAdvisorAnalysisData = {
    companyId: string;
    year: number;
};

export type TaxAdvisorReadTaxAdvisorAnalysisResponse = (TaxAdvisorAnalysis);

export type TaxAdvisorReadTaxRateBracketsData = {
    companyId: string;
    year: number;
};

export type TaxAdvisorReadTaxRateBracketsResponse = (Array<TaxRateBracketPublic>);

export type TaxAdvisorReadTaxPaymentsData = {
    companyId: string;
    year: number;
};

export type TaxAdvisorReadTaxPaymentsResponse = (TaxPaymentsPublic);

export type TaxAdvisorCreateTaxPaymentData = {
    companyId: string;
    requestBody: TaxPaymentCreate;
    year: number;
};

export type TaxAdvisorCreateTaxPaymentResponse = (TaxPaymentPublic);

export type TaxAdvisorDeleteTaxPaymentData = {
    companyId: string;
    paymentId: string;
    year: number;
};

export type TaxAdvisorDeleteTaxPaymentResponse = (Message);

export type TransactionImportsReadImportFieldsData = {
    importType: string;
};

export type TransactionImportsReadImportFieldsResponse = (ImportFieldList);

export type TransactionImportsValidateImportRecordsData = {
    requestBody: ImportValidationRequest;
};

export type TransactionImportsValidateImportRecordsResponse = (ImportValidationResponse);

export type TransactionImportsBulkInsertImportRecordsData = {
    requestBody: ImportBulkRequest;
};

export type TransactionImportsBulkInsertImportRecordsResponse = (ImportBulkResponse);

export type UploadsUploadCompanyLogoData = {
    formData: Body_uploads_upload_company_logo;
};

export type UploadsUploadCompanyLogoResponse = ({
    [key: string]: unknown;
});

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);