"""Update sale: notes + channel + date

Revision ID: 1e60a16278d5
Revises: 6ab27f254589
Create Date: 2026-05-11 16:21:11.166379

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1e60a16278d5'
down_revision = '6ab27f254589'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale', sa.Column('channel', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('sale', sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False))
    op.alter_column('sale', 'date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Date(),
               existing_nullable=False)
    op.drop_column('sale', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.alter_column('sale', 'date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_column('sale', 'notes')
    op.drop_column('sale', 'channel')
    # ### end Alembic commands ###
