"""add_email_verification

Revision ID: 254999af738b
Revises: 2f8b6c9d1a34
Create Date: 2026-07-23 16:10:11.614670

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '254999af738b'
down_revision = '2f8b6c9d1a34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emailverificationtoken',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emailverificationtoken_token_hash'), 'emailverificationtoken', ['token_hash'], unique=True)
    op.create_index(op.f('ix_emailverificationtoken_user_id'), 'emailverificationtoken', ['user_id'], unique=False)
    op.alter_column('bank_import_transactions', 'raw_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.drop_constraint('uq_company_ai_insights_company_id_module_type', 'company_ai_insights', type_='unique')
    op.create_unique_constraint('uq_companyaisummary_company_id_module_type', 'company_ai_insights', ['company_id', 'module_type'])
    op.alter_column('email_campaign', 'subject',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=500),
               existing_nullable=False)
    op.drop_index(op.f('ix_email_campaign_recipient_campaign_id'), table_name='email_campaign_recipient')
    op.drop_constraint(op.f('email_campaign_recipient_campaign_id_fkey'), 'email_campaign_recipient', type_='foreignkey')
    op.create_foreign_key(None, 'email_campaign_recipient', 'email_campaign', ['campaign_id'], ['id'])
    op.alter_column('email_template', 'name',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=255),
               existing_nullable=False)
    op.alter_column('email_template', 'subject',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=500),
               existing_nullable=False)
    op.drop_index(op.f('ix_recurring_conf_due'), table_name='recurring_conf')
    op.add_column('user', sa.Column('email_verified', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('user', sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True))
    # Backfill: mark all existing users as verified so they are not locked out.
    # Also stamp email_verified_at so the timestamp accurately reflects when
    # the migration ran (i.e. "verified as of this deployment").
    op.execute(
        "UPDATE \"user\" SET email_verified = true, "
        "email_verified_at = (NOW() AT TIME ZONE 'UTC') "
        "WHERE email_verified = false"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email_verified_at')
    op.drop_column('user', 'email_verified')
    op.create_index(op.f('ix_recurring_conf_due'), 'recurring_conf', ['status', 'next_run_date'], unique=False)
    op.alter_column('email_template', 'subject',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=500),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('email_template', 'name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'email_campaign_recipient', type_='foreignkey')
    op.create_foreign_key(op.f('email_campaign_recipient_campaign_id_fkey'), 'email_campaign_recipient', 'email_campaign', ['campaign_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_email_campaign_recipient_campaign_id'), 'email_campaign_recipient', ['campaign_id'], unique=False)
    op.alter_column('email_campaign', 'subject',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=500),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint('uq_companyaisummary_company_id_module_type', 'company_ai_insights', type_='unique')
    op.create_index(op.f('uq_company_ai_insights_company_id_module_type'), 'company_ai_insights', ['company_id', 'module_type'], unique=True)
    op.alter_column('bank_import_transactions', 'raw_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_index(op.f('ix_emailverificationtoken_user_id'), table_name='emailverificationtoken')
    op.drop_index(op.f('ix_emailverificationtoken_token_hash'), table_name='emailverificationtoken')
    op.drop_table('emailverificationtoken')
    # ### end Alembic commands ###
