"""Add company table

Revision ID: 4c943ea36ac6
Revises: 6b695f50882d
Create Date: 2026-05-11 21:55:23.095992

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4c943ea36ac6'
down_revision = '6b695f50882d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('registration_number', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('company_email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('company_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('company_address', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company')
    # ### end Alembic commands ###
