"""Add company_id and user_id to sale and purchase

Revision ID: 5f99cdaeb781
Revises: 4c943ea36ac6
Create Date: 2026-05-11 22:00:24.731441

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5f99cdaeb781'
down_revision = '4c943ea36ac6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('company_id', sa.Uuid(), nullable=True))
    op.add_column('purchase', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'purchase', 'company', ['company_id'], ['id'])
    op.create_foreign_key(None, 'purchase', 'user', ['user_id'], ['id'])
    op.add_column('sale', sa.Column('company_id', sa.Uuid(), nullable=True))
    op.add_column('sale', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'sale', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'sale', 'company', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sale', type_='foreignkey')
    op.drop_constraint(None, 'sale', type_='foreignkey')
    op.drop_column('sale', 'user_id')
    op.drop_column('sale', 'company_id')
    op.drop_constraint(None, 'purchase', type_='foreignkey')
    op.drop_constraint(None, 'purchase', type_='foreignkey')
    op.drop_column('purchase', 'user_id')
    op.drop_column('purchase', 'company_id')
    # ### end Alembic commands ###
