"""Add Purchase model

Revision ID: 6ab27f254589
Revises: cf108f247d9e
Create Date: 2026-05-11 11:22:48.071852

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6ab27f254589'
down_revision = 'cf108f247d9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase',
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('supplier_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('tax', sa.Float(), nullable=False),
    sa.Column('final_amount', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('invoice_no', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchase')
    # ### end Alembic commands ###
