"""Add purchase_category table

Revision ID: 6b695f50882d
Revises: 1e60a16278d5
Create Date: 2026-05-11 21:41:01.070918

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6b695f50882d'
down_revision = '1e60a16278d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchasecategory',
    sa.Column('categoryname', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchasecategory')
    # ### end Alembic commands ###
