"""add_document_default_note_table

Revision ID: 6c5314ae99ea
Revises: h1a2b3c4d5e9
Create Date: 2026-07-30 18:55:58.875527

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6c5314ae99ea'
down_revision = 'h1a2b3c4d5e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_default_note',
    sa.Column('document_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('default_notes_enabled', sa.Boolean(), nullable=False),
    sa.Column('default_notes', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'document_type')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_default_note')
    # ### end Alembic commands ###
