"""Add Bank Account model

Revision ID: 8d4e6f2a1c5b
Revises: b7c91f2e4a10
Create Date: 2026-06-12 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8d4e6f2a1c5b'
down_revision = 'b7c91f2e4a10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bankaccount',
    sa.Column('bank_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('account_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('account_number', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('account_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('opening_balance', sa.Float(), nullable=False),
    sa.Column('opening_date', sa.Date(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bankaccount')
    # ### end Alembic commands ###