"""Add role to user

Revision ID: 965dbfc819ae
Revises: 5f99cdaeb781
Create Date: 2026-05-11 22:11:18.313441

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '965dbfc819ae'
down_revision = '5f99cdaeb781'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable with a server default so existing rows get a value,
    # then update and make it non-nullable.
    op.add_column(
        'user',
        sa.Column(
            'role',
            sqlmodel.sql.sqltypes.AutoString(length=50),
            nullable=True,
            server_default=sa.text("'user'"),
        ),
    )
    # Ensure all existing rows have the default value (should be handled by server_default),
    # then alter the column to be non-nullable and remove server_default.
    op.alter_column('user', 'role', nullable=False, server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    # ### end Alembic commands ###
