"""Add docno to Document

Revision ID: a9f0b2e6c4d8
Revises: f4d127b9a8c3
Create Date: 2026-05-23 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a9f0b2e6c4d8'
down_revision = 'f4d127b9a8c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'document',
        sa.Column(
            'docno',
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
            server_default='',
        ),
    )
    op.alter_column('document', 'docno', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'docno')
    # ### end Alembic commands ###
