"""add_document_template_and_company_template_field

Revision ID: ba6778d3adc1
Revises: 6c5314ae99ea
Create Date: 2026-07-31 00:04:06.725411

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ba6778d3adc1'
down_revision = '6c5314ae99ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_template',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_template_code'), 'document_template', ['code'], unique=False)
    op.add_column('company', sa.Column('default_document_template_id', sa.Uuid(), nullable=True))

    # Seed default templates
    import uuid as _uuid
    from datetime import datetime, timezone
    now = datetime.now(timezone.utc)
    op.bulk_insert(
        sa.table(
            'document_template',
            sa.column('id', sa.Uuid()),
            sa.column('name', sa.String),
            sa.column('code', sa.String),
            sa.column('description', sa.String),
            sa.column('is_default', sa.Boolean),
            sa.column('is_active', sa.Boolean),
            sa.column('created_at', sa.DateTime(timezone=True)),
            sa.column('updated_at', sa.DateTime(timezone=True)),
        ),
        [
            {
                'id': _uuid.UUID('00000000-0000-0000-0000-000000000001'),
                'name': 'Basic',
                'code': 'basic',
                'description': 'Classic professional template. Clean and simple.',
                'is_default': True,
                'is_active': True,
                'created_at': now,
                'updated_at': now,
            },
            {
                'id': _uuid.UUID('00000000-0000-0000-0000-000000000002'),
                'name': 'Modern',
                'code': 'modern',
                'description': 'Modern corporate style with colored header and highlighted totals.',
                'is_default': False,
                'is_active': True,
                'created_at': now,
                'updated_at': now,
            },
        ],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'default_document_template_id')
    op.drop_index(op.f('ix_document_template_code'), table_name='document_template')
    op.drop_table('document_template')
    # ### end Alembic commands ###
