"""Add document running numbers to Company

Revision ID: c2d5e8f1a7b4
Revises: a9f0b2e6c4d8
Create Date: 2026-05-23 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2d5e8f1a7b4'
down_revision = 'a9f0b2e6c4d8'
branch_labels = None
depends_on = None


DOCUMENT_RUNNING_NUMBERS_DEFAULT = (
    '\'{"quotation": 1, "invoice": 1, "paymentvoucher": 1}\'::json'
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'company',
        sa.Column(
            'document_running_numbers',
            sa.JSON(),
            nullable=False,
            server_default=sa.text(DOCUMENT_RUNNING_NUMBERS_DEFAULT),
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'document_running_numbers')
    # ### end Alembic commands ###
