"""add_phone_number_to_client

Revision ID: d946243cde79
Revises: a8b939034139
Create Date: 2026-05-16 07:12:02.292340

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd946243cde79'
down_revision = 'a8b939034139'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'phone_number')
    # ### end Alembic commands ###
