"""Add price calculation to Document

Revision ID: e7a3b9c1d5f2
Revises: c2d5e8f1a7b4
Create Date: 2026-05-23 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7a3b9c1d5f2'
down_revision = 'c2d5e8f1a7b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'document',
        sa.Column(
            'price_calculation',
            sa.JSON(),
            nullable=False,
            server_default=sa.text("'{}'::json"),
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'price_calculation')
    # ### end Alembic commands ###
