/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EmailVerificationRequiredRouteImport } from './routes/email-verification-required'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as PaymentSuccessRouteImport } from './routes/payment.success'
import { Route as PaymentFailureRouteImport } from './routes/payment.failure'
import { Route as PaymentCancelRouteImport } from './routes/payment.cancel'
import { Route as LayoutUpgradeRouteImport } from './routes/_layout/upgrade'
import { Route as LayoutTransactionsRouteImport } from './routes/_layout/transactions'
import { Route as LayoutTaxAdvisorRouteImport } from './routes/_layout/tax-advisor'
import { Route as LayoutStaffRouteImport } from './routes/_layout/staff'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutSalesRouteImport } from './routes/_layout/sales'
import { Route as LayoutRecurringInvoicesRouteImport } from './routes/_layout/recurring-invoices'
import { Route as LayoutPurchasesRouteImport } from './routes/_layout/purchases'
import { Route as LayoutProductsRouteImport } from './routes/_layout/products'
import { Route as LayoutImportTransactionsRouteImport } from './routes/_layout/import-transactions'
import { Route as LayoutFinancialReportsRouteImport } from './routes/_layout/financial-reports'
import { Route as LayoutEmailBlastingRouteImport } from './routes/_layout/email-blasting'
import { Route as LayoutDocumentsRouteImport } from './routes/_layout/documents'
import { Route as LayoutDocumentSettingsRouteImport } from './routes/_layout/document-settings'
import { Route as LayoutCompaniesRouteImport } from './routes/_layout/companies'
import { Route as LayoutClientsRouteImport } from './routes/_layout/clients'
import { Route as LayoutBankReconciliationRouteImport } from './routes/_layout/bank-reconciliation'
import { Route as LayoutBankAccountsRouteImport } from './routes/_layout/bank-accounts'
import { Route as LayoutAuditLogsRouteImport } from './routes/_layout/audit-logs'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as DocumentsViewDocumentIdRouteImport } from './routes/documents.view.$documentId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailVerificationRequiredRoute =
  EmailVerificationRequiredRouteImport.update({
    id: '/email-verification-required',
    path: '/email-verification-required',
    getParentRoute: () => rootRouteImport,
  } as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment/success',
  path: '/payment/success',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentFailureRoute = PaymentFailureRouteImport.update({
  id: '/payment/failure',
  path: '/payment/failure',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCancelRoute = PaymentCancelRouteImport.update({
  id: '/payment/cancel',
  path: '/payment/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutUpgradeRoute = LayoutUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTransactionsRoute = LayoutTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTaxAdvisorRoute = LayoutTaxAdvisorRouteImport.update({
  id: '/tax-advisor',
  path: '/tax-advisor',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutStaffRoute = LayoutStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSalesRoute = LayoutSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRecurringInvoicesRoute = LayoutRecurringInvoicesRouteImport.update({
  id: '/recurring-invoices',
  path: '/recurring-invoices',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPurchasesRoute = LayoutPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProductsRoute = LayoutProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutImportTransactionsRoute =
  LayoutImportTransactionsRouteImport.update({
    id: '/import-transactions',
    path: '/import-transactions',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutFinancialReportsRoute = LayoutFinancialReportsRouteImport.update({
  id: '/financial-reports',
  path: '/financial-reports',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEmailBlastingRoute = LayoutEmailBlastingRouteImport.update({
  id: '/email-blasting',
  path: '/email-blasting',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDocumentsRoute = LayoutDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDocumentSettingsRoute = LayoutDocumentSettingsRouteImport.update({
  id: '/document-settings',
  path: '/document-settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCompaniesRoute = LayoutCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutClientsRoute = LayoutClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBankReconciliationRoute =
  LayoutBankReconciliationRouteImport.update({
    id: '/bank-reconciliation',
    path: '/bank-reconciliation',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutBankAccountsRoute = LayoutBankAccountsRouteImport.update({
  id: '/bank-accounts',
  path: '/bank-accounts',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuditLogsRoute = LayoutAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const DocumentsViewDocumentIdRoute = DocumentsViewDocumentIdRouteImport.update({
  id: '/documents/view/$documentId',
  path: '/documents/view/$documentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/email-verification-required': typeof EmailVerificationRequiredRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin': typeof LayoutAdminRoute
  '/audit-logs': typeof LayoutAuditLogsRoute
  '/bank-accounts': typeof LayoutBankAccountsRoute
  '/bank-reconciliation': typeof LayoutBankReconciliationRoute
  '/clients': typeof LayoutClientsRoute
  '/companies': typeof LayoutCompaniesRoute
  '/document-settings': typeof LayoutDocumentSettingsRoute
  '/documents': typeof LayoutDocumentsRoute
  '/email-blasting': typeof LayoutEmailBlastingRoute
  '/financial-reports': typeof LayoutFinancialReportsRoute
  '/import-transactions': typeof LayoutImportTransactionsRoute
  '/products': typeof LayoutProductsRoute
  '/purchases': typeof LayoutPurchasesRoute
  '/recurring-invoices': typeof LayoutRecurringInvoicesRoute
  '/sales': typeof LayoutSalesRoute
  '/settings': typeof LayoutSettingsRoute
  '/staff': typeof LayoutStaffRoute
  '/tax-advisor': typeof LayoutTaxAdvisorRoute
  '/transactions': typeof LayoutTransactionsRoute
  '/upgrade': typeof LayoutUpgradeRoute
  '/payment/cancel': typeof PaymentCancelRoute
  '/payment/failure': typeof PaymentFailureRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/documents/view/$documentId': typeof DocumentsViewDocumentIdRoute
}
export interface FileRoutesByTo {
  '/email-verification-required': typeof EmailVerificationRequiredRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin': typeof LayoutAdminRoute
  '/audit-logs': typeof LayoutAuditLogsRoute
  '/bank-accounts': typeof LayoutBankAccountsRoute
  '/bank-reconciliation': typeof LayoutBankReconciliationRoute
  '/clients': typeof LayoutClientsRoute
  '/companies': typeof LayoutCompaniesRoute
  '/document-settings': typeof LayoutDocumentSettingsRoute
  '/documents': typeof LayoutDocumentsRoute
  '/email-blasting': typeof LayoutEmailBlastingRoute
  '/financial-reports': typeof LayoutFinancialReportsRoute
  '/import-transactions': typeof LayoutImportTransactionsRoute
  '/products': typeof LayoutProductsRoute
  '/purchases': typeof LayoutPurchasesRoute
  '/recurring-invoices': typeof LayoutRecurringInvoicesRoute
  '/sales': typeof LayoutSalesRoute
  '/settings': typeof LayoutSettingsRoute
  '/staff': typeof LayoutStaffRoute
  '/tax-advisor': typeof LayoutTaxAdvisorRoute
  '/transactions': typeof LayoutTransactionsRoute
  '/upgrade': typeof LayoutUpgradeRoute
  '/payment/cancel': typeof PaymentCancelRoute
  '/payment/failure': typeof PaymentFailureRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/': typeof LayoutIndexRoute
  '/documents/view/$documentId': typeof DocumentsViewDocumentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/email-verification-required': typeof EmailVerificationRequiredRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/audit-logs': typeof LayoutAuditLogsRoute
  '/_layout/bank-accounts': typeof LayoutBankAccountsRoute
  '/_layout/bank-reconciliation': typeof LayoutBankReconciliationRoute
  '/_layout/clients': typeof LayoutClientsRoute
  '/_layout/companies': typeof LayoutCompaniesRoute
  '/_layout/document-settings': typeof LayoutDocumentSettingsRoute
  '/_layout/documents': typeof LayoutDocumentsRoute
  '/_layout/email-blasting': typeof LayoutEmailBlastingRoute
  '/_layout/financial-reports': typeof LayoutFinancialReportsRoute
  '/_layout/import-transactions': typeof LayoutImportTransactionsRoute
  '/_layout/products': typeof LayoutProductsRoute
  '/_layout/purchases': typeof LayoutPurchasesRoute
  '/_layout/recurring-invoices': typeof LayoutRecurringInvoicesRoute
  '/_layout/sales': typeof LayoutSalesRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/staff': typeof LayoutStaffRoute
  '/_layout/tax-advisor': typeof LayoutTaxAdvisorRoute
  '/_layout/transactions': typeof LayoutTransactionsRoute
  '/_layout/upgrade': typeof LayoutUpgradeRoute
  '/payment/cancel': typeof PaymentCancelRoute
  '/payment/failure': typeof PaymentFailureRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/_layout/': typeof LayoutIndexRoute
  '/documents/view/$documentId': typeof DocumentsViewDocumentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/email-verification-required'
    | '/login'
    | '/onboarding'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/admin'
    | '/audit-logs'
    | '/bank-accounts'
    | '/bank-reconciliation'
    | '/clients'
    | '/companies'
    | '/document-settings'
    | '/documents'
    | '/email-blasting'
    | '/financial-reports'
    | '/import-transactions'
    | '/products'
    | '/purchases'
    | '/recurring-invoices'
    | '/sales'
    | '/settings'
    | '/staff'
    | '/tax-advisor'
    | '/transactions'
    | '/upgrade'
    | '/payment/cancel'
    | '/payment/failure'
    | '/payment/success'
    | '/documents/view/$documentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/email-verification-required'
    | '/login'
    | '/onboarding'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/admin'
    | '/audit-logs'
    | '/bank-accounts'
    | '/bank-reconciliation'
    | '/clients'
    | '/companies'
    | '/document-settings'
    | '/documents'
    | '/email-blasting'
    | '/financial-reports'
    | '/import-transactions'
    | '/products'
    | '/purchases'
    | '/recurring-invoices'
    | '/sales'
    | '/settings'
    | '/staff'
    | '/tax-advisor'
    | '/transactions'
    | '/upgrade'
    | '/payment/cancel'
    | '/payment/failure'
    | '/payment/success'
    | '/'
    | '/documents/view/$documentId'
  id:
    | '__root__'
    | '/_layout'
    | '/email-verification-required'
    | '/login'
    | '/onboarding'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/_layout/admin'
    | '/_layout/audit-logs'
    | '/_layout/bank-accounts'
    | '/_layout/bank-reconciliation'
    | '/_layout/clients'
    | '/_layout/companies'
    | '/_layout/document-settings'
    | '/_layout/documents'
    | '/_layout/email-blasting'
    | '/_layout/financial-reports'
    | '/_layout/import-transactions'
    | '/_layout/products'
    | '/_layout/purchases'
    | '/_layout/recurring-invoices'
    | '/_layout/sales'
    | '/_layout/settings'
    | '/_layout/staff'
    | '/_layout/tax-advisor'
    | '/_layout/transactions'
    | '/_layout/upgrade'
    | '/payment/cancel'
    | '/payment/failure'
    | '/payment/success'
    | '/_layout/'
    | '/documents/view/$documentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  EmailVerificationRequiredRoute: typeof EmailVerificationRequiredRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  PaymentCancelRoute: typeof PaymentCancelRoute
  PaymentFailureRoute: typeof PaymentFailureRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  DocumentsViewDocumentIdRoute: typeof DocumentsViewDocumentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-verification-required': {
      id: '/email-verification-required'
      path: '/email-verification-required'
      fullPath: '/email-verification-required'
      preLoaderRoute: typeof EmailVerificationRequiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/payment/success': {
      id: '/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/failure': {
      id: '/payment/failure'
      path: '/payment/failure'
      fullPath: '/payment/failure'
      preLoaderRoute: typeof PaymentFailureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/cancel': {
      id: '/payment/cancel'
      path: '/payment/cancel'
      fullPath: '/payment/cancel'
      preLoaderRoute: typeof PaymentCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/upgrade': {
      id: '/_layout/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof LayoutUpgradeRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/transactions': {
      id: '/_layout/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof LayoutTransactionsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tax-advisor': {
      id: '/_layout/tax-advisor'
      path: '/tax-advisor'
      fullPath: '/tax-advisor'
      preLoaderRoute: typeof LayoutTaxAdvisorRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/staff': {
      id: '/_layout/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof LayoutStaffRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sales': {
      id: '/_layout/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof LayoutSalesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/recurring-invoices': {
      id: '/_layout/recurring-invoices'
      path: '/recurring-invoices'
      fullPath: '/recurring-invoices'
      preLoaderRoute: typeof LayoutRecurringInvoicesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/purchases': {
      id: '/_layout/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof LayoutPurchasesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/products': {
      id: '/_layout/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof LayoutProductsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/import-transactions': {
      id: '/_layout/import-transactions'
      path: '/import-transactions'
      fullPath: '/import-transactions'
      preLoaderRoute: typeof LayoutImportTransactionsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/financial-reports': {
      id: '/_layout/financial-reports'
      path: '/financial-reports'
      fullPath: '/financial-reports'
      preLoaderRoute: typeof LayoutFinancialReportsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/email-blasting': {
      id: '/_layout/email-blasting'
      path: '/email-blasting'
      fullPath: '/email-blasting'
      preLoaderRoute: typeof LayoutEmailBlastingRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/documents': {
      id: '/_layout/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof LayoutDocumentsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/document-settings': {
      id: '/_layout/document-settings'
      path: '/document-settings'
      fullPath: '/document-settings'
      preLoaderRoute: typeof LayoutDocumentSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/companies': {
      id: '/_layout/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof LayoutCompaniesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/clients': {
      id: '/_layout/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof LayoutClientsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/bank-reconciliation': {
      id: '/_layout/bank-reconciliation'
      path: '/bank-reconciliation'
      fullPath: '/bank-reconciliation'
      preLoaderRoute: typeof LayoutBankReconciliationRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/bank-accounts': {
      id: '/_layout/bank-accounts'
      path: '/bank-accounts'
      fullPath: '/bank-accounts'
      preLoaderRoute: typeof LayoutBankAccountsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/audit-logs': {
      id: '/_layout/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof LayoutAuditLogsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/documents/view/$documentId': {
      id: '/documents/view/$documentId'
      path: '/documents/view/$documentId'
      fullPath: '/documents/view/$documentId'
      preLoaderRoute: typeof DocumentsViewDocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutAuditLogsRoute: typeof LayoutAuditLogsRoute
  LayoutBankAccountsRoute: typeof LayoutBankAccountsRoute
  LayoutBankReconciliationRoute: typeof LayoutBankReconciliationRoute
  LayoutClientsRoute: typeof LayoutClientsRoute
  LayoutCompaniesRoute: typeof LayoutCompaniesRoute
  LayoutDocumentSettingsRoute: typeof LayoutDocumentSettingsRoute
  LayoutDocumentsRoute: typeof LayoutDocumentsRoute
  LayoutEmailBlastingRoute: typeof LayoutEmailBlastingRoute
  LayoutFinancialReportsRoute: typeof LayoutFinancialReportsRoute
  LayoutImportTransactionsRoute: typeof LayoutImportTransactionsRoute
  LayoutProductsRoute: typeof LayoutProductsRoute
  LayoutPurchasesRoute: typeof LayoutPurchasesRoute
  LayoutRecurringInvoicesRoute: typeof LayoutRecurringInvoicesRoute
  LayoutSalesRoute: typeof LayoutSalesRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutStaffRoute: typeof LayoutStaffRoute
  LayoutTaxAdvisorRoute: typeof LayoutTaxAdvisorRoute
  LayoutTransactionsRoute: typeof LayoutTransactionsRoute
  LayoutUpgradeRoute: typeof LayoutUpgradeRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutAuditLogsRoute: LayoutAuditLogsRoute,
  LayoutBankAccountsRoute: LayoutBankAccountsRoute,
  LayoutBankReconciliationRoute: LayoutBankReconciliationRoute,
  LayoutClientsRoute: LayoutClientsRoute,
  LayoutCompaniesRoute: LayoutCompaniesRoute,
  LayoutDocumentSettingsRoute: LayoutDocumentSettingsRoute,
  LayoutDocumentsRoute: LayoutDocumentsRoute,
  LayoutEmailBlastingRoute: LayoutEmailBlastingRoute,
  LayoutFinancialReportsRoute: LayoutFinancialReportsRoute,
  LayoutImportTransactionsRoute: LayoutImportTransactionsRoute,
  LayoutProductsRoute: LayoutProductsRoute,
  LayoutPurchasesRoute: LayoutPurchasesRoute,
  LayoutRecurringInvoicesRoute: LayoutRecurringInvoicesRoute,
  LayoutSalesRoute: LayoutSalesRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutStaffRoute: LayoutStaffRoute,
  LayoutTaxAdvisorRoute: LayoutTaxAdvisorRoute,
  LayoutTransactionsRoute: LayoutTransactionsRoute,
  LayoutUpgradeRoute: LayoutUpgradeRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  EmailVerificationRequiredRoute: EmailVerificationRequiredRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  PaymentCancelRoute: PaymentCancelRoute,
  PaymentFailureRoute: PaymentFailureRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  DocumentsViewDocumentIdRoute: DocumentsViewDocumentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
